### ISSUE TITLE
CSS 404's with ``mkdocs serve``

### ISSUE THREAD

**Issue by dei-layborer** [TEParsons/mkdocs-torillic#2]
This is a strange one.  When using this theme via ``mkdocs serve``, the CSS fails to load with the following message:

```
WARNING -  [11:38:00] "GET /css/torillic/torillic.css HTTP/1.1" code 404
```

Note the extra sub-directory that it's looking for.  I can't see any reason why it's doing this, but it doesn't happen with other themes.

**Comment by 502E532E** [comment]
It works if you copy the `torillic`-folder from https://github.com/TEParsons/torillic into the `css` folder from this repo.

I needed some time to figure this out myself as well, @TEParsons would it be possible to mention this in the README (or CONTRIBUTING), or better to automate it?

**Comment by TEParsons** [comment]
Happy to document it, yes!

Though, you shouldn't actually need to copy the folder yourself - if you install `mkdocs-torillic` from PyPi then you should (unless I've messed something up with the Build action) get that folder included. If you're running from a clone/download of this repo, then you should use the `last-release` branch instead as that's also got that folder copied in already.

The reason it's set up like this is that the base folder applies to both mkdocs and Typora, so it's easier to copy the base theme over when building a release than it would be to maintain two copies of it on different repos.

**Comment by TEParsons** [comment]
Documented here:

https://github.com/TEParsons/mkdocs-torillic/commit/20ca86fc6600f23bfd08f005f795ce63d7ad57f2
